package kr.co.fiven.sdadivingapi.vo;

import lombok.Data;

@Data
public class PlayerList {
    private Long gamememberidx;
    private int gubun;
    private String gametime;
    private String gametimeend;
    private String place;
    private Long playeridx;
    private String username;
    private String gbidx;
    private String levelno;
    private String cda;
    private String cdanm;
    private String cdb;
    private String cdbnm;
    private String cdc;
    private String cdcnm;
    private int tryoutgroupno;
    private int tryoutsortno;
    private int tryoutstateno;
    private String tryoutresult ;
    private int roundno;
    private int sortno;
    private int stateno;
    private String gameresult;
    private String team;
    private String teamnm;
    private String userclass;
    private String sex;
    private int requestidx;
    private String bestscore;
    private int bestorder;
    private String bestcdbnm;
    private int bestidx;
    private String bestdate;
    private String besttitle;
    private String bestgamecode;
    private String bestarea;
    private String starttype;
    private String ksportsno;
    private String kno;
    private String sidonm;
    private int tryouttotalorder;
    private String tryoutorder;
    private String gameorder;
    private Long rgamelevelidx;
    private Long gametitleidx;
    private int gubunam;
    private String tryoutgamedate;
    private String tryoutgamestarttime;
    private String gameno;
    private int tryoutgameings;
    private String g1firstrc;
    private String g1korsin;
    private String g1gamesin;
    private String g1firstmembersin;
    private String g2firstrc;
    private String g2korsin;
    private String g2gamesin;
    private String g2firstmembersin;
    private String itgubun;
    private int setcodecount;
    private String player1;
    private Long  player1partneridx;
    private String player2;
    private Long  player2partneridx;
}
